name: Publish to GitHub Pages

on:
  push:
    branches:
      - main

env:
  FLUTTER_VERSION: 3.32.0

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: kuhnroyal/flutter-fvm-config-action/setup@v3
      - uses: bluefireteam/flutter-gh-pages@v7
        with:
          workingDir: example
          baseHref: /phoenix_theme/
          webRenderer: canvaskit
          customArgs: --no-tree-shake-icons